package menuutama;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;

/**
 *
 * @author Siti Mawaddah
 */
public class DataLaptop extends javax.swing.JPanel {
    // koneksi mysql
    private Connection conn = new Koneksi().connect();
    private DialogTambahData dialog = new DialogTambahData(null, true);
    public DefaultTableModel tabmode;
    private String noId;

    /**
     * Creates new form NewJPanel
     */
    public DataLaptop() {
        initComponents();
        updateDataTabel();
    }

    /**
     * mendapatkan Data Tabel dari database
     */
    protected void updateDataTabel() {
        Object[] Baris = {
                "Id Laptop",
                "Nama Laptop",
                "Merk",
                "Harga",
                "Processor",
                "RAM",
                "Storage",
                "Battery Life",
                "Performa",
                "Kategori Harga",
                "Kategori Penyimpanan",
                "Kategori Daya Tahan",
                "Kategori RAM"
        };

        tabmode = new DefaultTableModel(null, Baris);
        tabelDataLaptop.setModel(tabmode);

        String sql = "SELECT * FROM data_laptop ORDER BY id_laptop";

        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String a = hasil.getString("id_laptop");
                String b = hasil.getString("nama_laptop");
                String c = hasil.getString("merk");
                String d = hasil.getString("harga");
                String e = hasil.getString("processor");
                String f = hasil.getString("ram");
                String g = hasil.getString("storage");
                String h = hasil.getString("battery_life");
                String i = hasil.getString("performa");
                String j = hasil.getString("kategori_harga");
                String k = hasil.getString("kategori_penyimpanan");
                String l = hasil.getString("kategori_daya_tahan");
                String m = hasil.getString("kategori_ram");

                String[] data = { a, b, c, d, e, f, g, h, i, j, k, l, m };
                tabmode.addRow(data);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * Mendapatkan Data dari Tabel
     */
    private void getDataTabel() {
        int bar = tabelDataLaptop.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();
        String h = tabmode.getValueAt(bar, 7).toString();
        String i = tabmode.getValueAt(bar, 8).toString();
        String j = tabmode.getValueAt(bar, 9).toString();
        String k = tabmode.getValueAt(bar, 10).toString();
        String l = tabmode.getValueAt(bar, 11).toString();
        String m = tabmode.getValueAt(bar, 12).toString();

        noId = a;
        dialog.setDataTabel(a, b, c, d, e, f, g, h, i, j, k, l, m);
    }

    protected void hapusDataLaptop() {
        if (noId != null) {
            int ok = JOptionPane.showConfirmDialog(null, "hapus", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
            if (ok == 0) {
                String sql = "DELETE FROM data_laptop WHERE id_laptop='" + noId + "'";
                try {
                    PreparedStatement stat = conn.prepareStatement(sql);
                    stat.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                    updateDataTabel();
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Data gagal dihapus " + e);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Silahkan pilih data yang akan dihapus");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judul = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tombolTambah = new javax.swing.JButton();
        tombolUbah = new javax.swing.JButton();
        tombolHapus = new javax.swing.JButton();
        tombolUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataLaptop = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        judul.setBackground(new java.awt.Color(22, 65, 53));
        judul.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 237, 192));
        judul.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        judul.setText("  Data Laptop");
        judul.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 237, 192));

        jPanel2.setBackground(new java.awt.Color(255, 237, 192));

        tombolTambah.setBackground(new java.awt.Color(22, 65, 53));
        tombolTambah.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tombolTambah.setForeground(new java.awt.Color(255, 255, 255));
        tombolTambah.setText("Tambah");
        tombolTambah.setBorder(null);
        tombolTambah.setPreferredSize(new java.awt.Dimension(71, 35));
        tombolTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolTambahActionPerformed(evt);
            }
        });

        tombolUbah.setBackground(new java.awt.Color(22, 65, 53));
        tombolUbah.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tombolUbah.setForeground(new java.awt.Color(255, 255, 255));
        tombolUbah.setText("Ubah");
        tombolUbah.setBorder(null);
        tombolUbah.setPreferredSize(new java.awt.Dimension(35, 35));
        tombolUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolUbahActionPerformed(evt);
            }
        });

        tombolHapus.setBackground(new java.awt.Color(22, 65, 53));
        tombolHapus.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tombolHapus.setForeground(new java.awt.Color(255, 255, 255));
        tombolHapus.setText("Hapus");
        tombolHapus.setBorder(null);
        tombolHapus.setPreferredSize(new java.awt.Dimension(35, 35));
        tombolHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHapusActionPerformed(evt);
            }
        });

        tombolUpdate.setBackground(new java.awt.Color(22, 65, 53));
        tombolUpdate.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tombolUpdate.setForeground(new java.awt.Color(255, 255, 255));
        tombolUpdate.setText("Update");
        tombolUpdate.setBorder(null);
        tombolUpdate.setPreferredSize(new java.awt.Dimension(71, 35));
        tombolUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(tombolTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 91,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tombolUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 91,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tombolHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 91,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tombolUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 91,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tombolTambah, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tombolUbah, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tombolHapus, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tombolUpdate, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(15, Short.MAX_VALUE)));

        tabelDataLaptop.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tabelDataLaptop.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "ID Laptop", "Nama Laptop", "Merk", "Harga", "Processor", "RAM", "Storage", "Battery Life",
                        "Performa", "Kategori Harga", "Kategori Penyimpanan", "Kategori Daya Tahan", "Kategori RAM"
                }));
        tabelDataLaptop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataLaptopMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDataLaptop);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
                                .addGap(20, 20, 20)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                                .addGap(20, 20, 20)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 69,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void tombolTambahActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tombolTambahActionPerformed
        // TODO add your handling code here:
        // dialog.judul.setText("TAMBAH DATA LAPTOP");
        // dialog.tombolEdit.setVisible(false);
        // dialog.tombolTambah.setVisible(true);
        dialog.setVisible(true);
        dialog.kosong();
        updateDataTabel();
    }// GEN-LAST:event_tombolTambahActionPerformed

    private void tombolUbahActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tombolUbahActionPerformed
        // TODO add your handling code here:
        if (noId != null) {
            // dialog.judul.setText("UBAH DATA LAPTOP");
            // dialog.tombolEdit.setVisible(true);
            // dialog.tombolTambah.setVisible(false);
            dialog.setVisible(true);
            getDataTabel();
            updateDataTabel();
        } else {
            JOptionPane.showMessageDialog(null, "Silahkan pilih data yang akan diubah");
        }
    }// GEN-LAST:event_tombolUbahActionPerformed

    private void tombolHapusActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tombolHapusActionPerformed
        // TODO add your handling code here:
        hapusDataLaptop();
    }// GEN-LAST:event_tombolHapusActionPerformed

    private void tombolUpdateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tombolUpdateActionPerformed
        // TODO add your handling code here:
        updateDataTabel();
    }// GEN-LAST:event_tombolUpdateActionPerformed

    private void tabelDataLaptopMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tabelDataLaptopMouseClicked
        // TODO add your handling code here:
        getDataTabel();
    }// GEN-LAST:event_tabelDataLaptopMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul;
    private javax.swing.JTable tabelDataLaptop;
    private javax.swing.JButton tombolHapus;
    private javax.swing.JButton tombolTambah;
    private javax.swing.JButton tombolUbah;
    private javax.swing.JButton tombolUpdate;
    // End of variables declaration//GEN-END:variables
}
